# Terraform Provider release workflow.
name: Release

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:
  push:
    branches:
      - master
      - main

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Set
        run: | 
          echo "TIMESTAMP=$(date +%Y%m%d)" >> "$GITHUB_ENV"
      - name: Test
        run: |
          echo "${TIMESTAMP}"
